# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext-rnaseq-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8
  - star=2.6.1d # don't upgrade me - 2.7X indices incompatible with iGenomes.
  - hisat2=2.1.0
  - picard=2.18.27
  - rseqc=2.6.2
  - samtools=1.3
  - subread=1.6.4
  - multiqc=1.7
  - tophat=2.1.1
  - rsem=1.3.1
  - bowtie2=2.3.5
  - bowtie=1.2.2
  - trimmomatic=0.39
  - igvtools=2.5.3
  - bedtools=2.27.1
  - fastx_toolkit=0.0.14
  - ucsc-wigToBigWig=366